
version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
       - ./:/usr/src/app
    networks:
      - network

networks:
  network: {}